version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 739275480317.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t brain_task_app .
      - docker tag brain_task_app:latest 739275480317.dkr.ecr.ap-south-1.amazonaws.com/brain_task_app:latest

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 739275480317.dkr.ecr.ap-south-1.amazonaws.com/brain_task_app:latest
      - echo Writing image definitions...
      - printf '[{"name":"brain_task_app","imageUri":"739275480317.dkr.ecr.ap-south-1.amazonaws.com/brain_task_app:latest"}]' > imagedefinitions.json
      - echo Updating kubeconfig...
      - aws eks update-kubeconfig --region ap-south-1 --name my-cluster


artifacts:
  files:
    - k8s/*
