apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-task-app
  labels:
    app: brain-task-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brain-task-app
  template:
    metadata:
      labels:
        app: brain-task-app
    spec:
      containers:
        - name: brain-task-app
          image: 739275480317.dkr.ecr.ap-south-1.amazonaws.com/brain_task_app:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always  # <-- Optional but recommended for latest tags

---

apiVersion: v1
kind: Service
metadata:
  name: brain-task-service
spec:
  type: LoadBalancer
  selector:
    app: brain-task-app
  ports:
    - port: 3000       # Client-facing port (external)
      targetPort: 3000  # Matches containerPort
      protocol: TCP